name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - run: composer update --no-interaction --no-plugins --no-scripts --prefer-dist --no-progress

      - run: composer validate --strict --no-plugins
      - run: composer test --no-plugins
